### PR TITLE
Don't crash in bdist_rpm with unicode issues.

### PR DESCRIPTION
**Pull request by kivikakk**
Would like to keep our changes in one repo, but I can't push to yours!

### CODE REVIEW

**Comment by levic** [comment]
Is it possible to make a pull request to upstream?

I can then pull that back in, your change is more likely to get accepted
(they wanted a demonstration test case for my changes which I haven't got
around to doing).

On 6 February 2015 at 20:30, Yuki Izumi notifications@github.com wrote:

> ## Would like to keep our changes in one repo, but I can't push to yours!
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/levic/django-floppyforms/pull/1
> Commit Summary
> - Don't crash in bdist_rpm with unicode issues.
> 
> File Changes
> - _M_ setup.py
>   https://github.com/levic/django-floppyforms/pull/1/files#diff-0 (2)
> 
> Patch Links:
> - https://github.com/levic/django-floppyforms/pull/1.patch
> - https://github.com/levic/django-floppyforms/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/levic/django-floppyforms/pull/1.

## 

Kind Regards,

---

Alliance Software
Joining forces with Web Elements

Ph: 03 9955 7000
Fax: 03 9894 2106
Email: levi.cameron@alliancesoftware.com.au
Web: www.alliancesoftware.com.au

**Comment by kivikakk** [comment]
I'll try. I feel like the change might seem niche, or more likely, a problem with setuptools.

**Comment by kivikakk** [comment]
This has been merged upstream.

**Comment by levic** [comment]
Have merged upstream changes into my floppyforms repo

On 10 February 2015 at 10:19, Yuki Izumi notifications@github.com wrote:

> This has been merged upstream.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/levic/django-floppyforms/pull/1#issuecomment-73612518
> .

## 

Kind Regards,

---

Alliance Software
Joining forces with Web Elements

Ph: 03 9955 7000
Fax: 03 9894 2106
Email: levi.cameron@alliancesoftware.com.au
Web: www.alliancesoftware.com.au

**Pull request closed without merging**
